version: '3.4'

services:
  postgres:
    build:
      context: .
      dockerfile: build/db/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./build/db/scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: shortener-api

networks:
  kind:
    external: true